### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by PericlesHat** [yanx27/CLEVR3D#2]
Hi authors,

I found another issue in your dataset. The trainning process terminated with an **KeyError** in
https://github.com/yanx27/CLEVR3D/blob/ad6e5ed019d27b0d1f96fa72beb3ecdfb51bbc41/dataset/R3ScanO27R16Dataset.py#L273
that `self.scene_graph` lacks some scans. For example, scan `352e9c48-69fb-27a7-8a35-3dbf699637c8` can be found in `CLEVR3D-REAL.json` but **does not exsist** in `SceneGraphAnnotation.json`, which means the questions and scene graphs do not match.

Such error can be avoided by skipping the unmatchings. However, I think you may have provided the wrong dataset, as the name of `R3ScanO27R16Dataset.py` represents a smaller version of 3DSSG (or 3RScan) which only contains 27 objects and 16 relations. `SceneGraphAnnotation.json` also lacks some scans that exsist in `CLEVR3D-REAL.json`.

Thanks for your time!

**Comment by CurryYuan** [comment]
Thank you for the comment, we have fixed it.
